"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { demoServices } from "@/lib/demo-data";
import type { CityService } from "@/types";
export default function ServiceDetailPage() {
  const { slug } = useParams<{ slug: string }>(); const [service, setService] = useState<CityService | null>(demoServices.find((item) => item.slug === slug) || null);
  useEffect(() => { fetch("/api/services").then((r) => r.ok ? r.json() : null).then((r) => { if (!Array.isArray(r?.data)) return; const item = r.data.find((entry: Record<string, unknown>) => entry.slug === slug); setService(item ? { id: String(item.id), slug, name: String(item.name), category: String(item.category), description: String(item.description), duration: `${item.durationDays || 5} أيام عمل`, fee: Number(item.feeIls) ? "رسوم تجريبية" : "دون رسوم تجريبية", status: String(item.status) as CityService["status"], requirements: item.requirements as string[], steps: item.steps as string[], icon: String(item.icon || "✦") } : null); }).catch(() => undefined); }, [slug]);
  if (!service) return <main className="page-content"><div className="empty-state">الخدمة غير موجودة. <Link href="/services">العودة إلى الخدمات</Link></div></main>;
  return <><section className="page-hero"><div className="breadcrumbs"><Link href="/">الرئيسية</Link> / <Link href="/services">الخدمات</Link> / {service.name}</div><h1>{service.name}</h1><p>{service.description}</p></section><main className="page-content"><div className="content-grid"><section className="surface"><span className="section-kicker">قبل أن تبدأ</span><h2>متطلبات الخدمة</h2><ul className="detail-list">{service.requirements.map((value) => <li key={value}>{value}</li>)}</ul><div className="service-facts"><span><small>المدة التقديرية</small><strong>{service.duration}</strong></span><span><small>الرسوم</small><strong>{service.fee}</strong></span><span><small>الحالة</small><strong>متاحة تجريبيًا</strong></span></div><span className="demo-label">المدد والرسوم بيانات توضيحية فقط.</span><div style={{ marginTop: 19 }}><Link href={`/account/requests?new=${service.slug}`} className="button button-primary">ابدأ الخدمة <span>←</span></Link></div></section><section className="surface"><span className="section-kicker">خطوات الإجراء</span><h2>كيف تسير معاملتك؟</h2><div className="request-timeline">{service.steps.map((step, index) => <div key={step} className={`timeline-row${index === 0 ? " done" : ""}`}><span className="timeline-dot" /><span><strong>{step}</strong><small>{index === 0 ? "تبدأ عند إرسال الطلب" : "يظهر تحديث الحالة في حسابك"}</small></span></div>)}</div><p>يتلقى حسابك إشعارًا عند تسجيل الطلب أو تغير حالته. رقم المرجع يساعدك في التواصل مع البلدية.</p></section></div></main></>;
}
