"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import dynamic from "next/dynamic";
import { demoFacilities, demoProjects, demoServices, mapCenter } from "@/lib/demo-data";
import type { CityService, MapFeature } from "@/types";
import Reveal from "@/components/Reveal";
const MapView = dynamic(() => import("@/components/MapView"), { ssr: false, loading: () => <div className="map-skeleton"><span className="pulse-dot" /> تجهيز خريطة البريج...</div> });
export default function HomePage() {
  const [selected, setSelected] = useState<MapFeature | null>(null); const [now, setNow] = useState("");
  const [projects, setProjects] = useState<MapFeature[]>(demoProjects); const [services, setServices] = useState<CityService[]>(demoServices); const [features, setFeatures] = useState<MapFeature[]>([...demoProjects, ...demoFacilities]); const [center, setCenter] = useState(mapCenter); const [zoom, setZoom] = useState(14.8);
  useEffect(() => { const update = () => setNow(new Intl.DateTimeFormat("ar-PS", { timeZone: "Asia/Gaza", hour: "2-digit", minute: "2-digit", day: "numeric", month: "long" }).format(new Date())); update(); const id = window.setInterval(update, 60_000); return () => window.clearInterval(id); }, []);
  useEffect(() => {
    fetch("/api/map-data").then((response) => response.ok ? response.json() : null).then((data) => { if (!data) return; const projectRows = (data.projects || []) as MapFeature[]; const facilityRows = (data.facilities || []) as MapFeature[]; const complaintRows = (data.complaints || []) as MapFeature[]; setProjects(projectRows); setFeatures([...projectRows, ...facilityRows, ...complaintRows]); if (data.center) setCenter(data.center); if (typeof data.zoom === "number") setZoom(data.zoom); }).catch(() => undefined);
    fetch("/api/services").then((response) => response.ok ? response.json() : null).then((result) => { if (result?.data?.length) setServices(result.data.map((row: Record<string, unknown>) => ({ id: String(row.id), slug: String(row.slug), name: String(row.name), category: String(row.category), description: String(row.description), duration: `${row.durationDays || 5} أيام عمل`, fee: Number(row.feeIls) ? "رسوم تجريبية" : "دون رسوم تجريبية", status: String(row.status) as CityService["status"], requirements: (row.requirements || []) as string[], steps: (row.steps || []) as string[], icon: String(row.icon || "✦") }))); }).catch(() => undefined);
  }, []);
  const quickServices = services.filter((service) => service.status === "ACTIVE").slice(0, 4);
  return <main className="home-page">
    <section className="hero-section"><div className="hero-copy"><div className="eyebrow"><i /> منصة المدينة الذكية <span>الإصدار التجريبي</span></div><h1>مدينة تعمل<br /><em>من أجلك.</em></h1><p className="hero-lede">خدمات البلدية، نبض المدينة، وصوت المجتمع —<br />تجربة رقمية واحدة تضع الإنسان في المركز.</p><div className="hero-buttons"><Link href="/services" className="button button-primary">اكتشف الخدمات <span>←</span></Link><Link href="/transparency" className="button button-outline">استكشف المشاريع <span>↗</span></Link></div><div className="hero-meta"><span><i className="pulse-dot" /> نظام المدينة <b>في مرحلة تجريبية</b></span><span>◷ {now || "--:--"} <small>توقيت المدينة</small></span></div><div className="hero-city-stats"><div><strong>4.2 <small>كم²</small></strong><span>نطاق العرض</span></div><div><strong>{services.filter((service) => service.status === "ACTIVE").length}</strong><span>خدمات تجريبية</span></div><div><strong>{String(projects.length).padStart(2, "0")}</strong><span>مشاريع توضيحية</span></div></div></div>
      <div className="hero-map-wrap"><Link href="/city-guide" className="hero-map-label" aria-label="فتح دليل الخريطة"><span className="live-indicator">●</span><div><strong>البريج — قطاع غزة</strong><small>خريطة تفاعلية ثلاثية الأبعاد</small></div><span className="map-open-arrow">↗</span></Link><MapView features={features} center={center} initialZoom={zoom} activeId={selected?.id} onSelect={setSelected} /><div className="map-legend"><span><i className="legend-project" /> مشروع</span><span><i className="legend-place" /> مرفق</span><span className="weather-demo"><b>☀ 22°</b><small>طقس توضيحي</small></span></div>{selected && <div className="map-selected"><small>{selected.category}</small><strong>{selected.name}</strong><button onClick={() => setSelected(null)} aria-label="إغلاق">×</button></div>}<div className="map-coordinates"><span>{center.latitude.toFixed(4)}°N</span><i /> <span>{center.longitude.toFixed(4)}°E</span></div></div>
    </section>
    <section className="ticker-strip"><div className="ticker-date"><small>اليوم</small><strong>{now || ""}</strong></div><div className="ticker-status"><i className="status-mark">✳</i><span>حالة المنصة</span><strong>تشغيل تجريبي</strong></div><div className="ticker-alert"><span className="alert-icon">!</span><div><small>تنبيه معلوماتي</small><strong>كل الأرقام والمواقع المعروضة بيانات تجريبية وليست بيانات رسمية.</strong></div><Link href="/transparency">اعرف المزيد ←</Link></div><div className="ticker-weather"><span>☼</span><div><strong>22°</strong><small>طقس تجريبي</small></div></div></section>
    <section className="quick-services section-frame"><div className="section-heading"><div><span className="section-kicker">بوابة الخدمات</span><h2>ما الذي تحتاجه اليوم؟</h2><p>ابدأ خدمتك مباشرة وتابع خطواتها من حسابك.</p></div><Link href="/services" className="text-link">كل الخدمات <span>←</span></Link></div><div className="service-tiles">{quickServices.map((service, index) => <Reveal key={service.id} delay={index * .055}><Link href={`/services/${service.slug}`} className={`service-tile tile-${index}`}><span className="tile-number">0{index + 1}</span><span className="tile-icon">{service.icon}</span><strong>{service.name}</strong><small>{service.category}</small><span className="tile-arrow">↗</span></Link></Reveal>)}</div></section>
    <section className="home-lower section-frame"><div className="home-project-panel"><div className="section-heading"><div><span className="section-kicker">على الخريطة</span><h2>مشاريع المدينة</h2></div><Link href="/transparency" className="text-link">لوحة الشفافية ←</Link></div>{projects.slice(0, 3).map((project, index) => <button className="project-list-item" key={project.id} onClick={() => { setSelected(project); window.scrollTo({ top: 0, behavior: "smooth" }); }}><span className="project-index">{String(index + 1).padStart(2, "0")}</span><span><strong>{project.name}</strong><small>{project.description}</small></span><span className="progress-mini"><i style={{ width: `${project.progress || 0}%` }} /></span><span className="progress-value">{project.progress || 0}%</span><span className="tile-arrow">↗</span></button>)}<small className="demo-caption">نسب الإنجاز الموضحة تجريبية لأغراض العرض.</small></div><div className="home-side-card"><span className="side-card-orbit">✳</span><span className="section-kicker">صوت المجتمع</span><h3>التغيير يبدأ<br />بفكرة منك.</h3><p>شارك اقتراحك أو أضف صوتك لاستطلاع أولويات المدينة.</p><Link href="/participation" className="button button-dark">شارك الآن <span>←</span></Link><div className="side-card-foot"><span>مشاركة مجتمعية</span><small>ميزة تجريبية</small></div></div></section>
    <section className="city-note"><span>ب</span><p><strong>البريج أقرب إليك.</strong> بوابة موحدة للخدمات البلدية والمعلومات ومشاركة المجتمع — ضمن نموذج تجريبي قابل للتخصيص للبلديات.</p><Link href="/about">عن المنصة ↗</Link></section>
  </main>;
}
