"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { usePathname } from "next/navigation";
import dynamic from "next/dynamic";
import type { MapFeature, MunicipalityProfile } from "@/types";
const MapView = dynamic(() => import("@/components/MapView"), { ssr: false });
type Data = Record<string, unknown>;
const sections = [
  ["نظرة عامة", "overview", "◫"], ["الخدمات", "services", "▤"], ["الطلبات", "requests", "⇢"], ["الشكاوى", "complaints", "⚑"], ["المشاريع", "projects", "◆"], ["المرافق", "facilities", "⌖"], ["الأخبار", "news", "▧"], ["الإعلانات", "announcements", "!"], ["الفعاليات", "events", "◷"], ["المواعيد", "appointments", "◉"], ["الإشعارات", "notifications", "✳"], ["الاستطلاعات", "surveys", "☷"], ["المقترحات", "proposals", "✦"], ["المستخدمون", "users", "♙"], ["الموظفون", "employees", "♧"], ["إعدادات البلدية", "settings", "⚙"], ["بيانات الخريطة", "map-data", "⌖"], ["التحليلات", "analytics", "▥"], ["سجل التدقيق", "audit-log", "◌"], ["البلديات", "municipalities", "▦"]
] as const;
const names: Record<string, string> = Object.fromEntries(sections.map(([name, key]) => [key, name]));
const titles: Record<string, string> = { services: "الخدمة", projects: "المشروع", facilities: "المرفق", news: "الخبر", events: "الفعالية", announcements: "الإعلان", surveys: "الاستطلاع", employees: "الموظف", users: "المستخدم", notifications: "الإشعار" };
const fields: Record<string, [string, string, unknown?][]> = {
  services: [["name", "اسم الخدمة"], ["slug", "رابط الخدمة (slug)"], ["category", "التصنيف"], ["description", "الوصف", "textarea"], ["requirements", "المتطلبات — كل بند بسطر", "array"], ["documents", "المستندات — كل بند بسطر", "array"], ["steps", "الخطوات — كل بند بسطر", "array"], ["durationDays", "المدة (أيام)", "number"], ["feeIls", "رسوم تجريبية (ILS)", "number"], ["icon", "رمز"], ["status", "الحالة", ["ACTIVE", "INACTIVE"]]],
  projects: [["name", "اسم المشروع"], ["slug", "الرابط"], ["description", "الوصف", "textarea"], ["imageUrl", "رابط صورة المشروع"], ["latitude", "خط العرض", "number"], ["longitude", "خط الطول", "number"], ["progress", "نسبة الإنجاز", "number"], ["status", "الحالة", ["PLANNED", "IN_PROGRESS", "COMPLETED", "PAUSED"]], ["startsAt", "تاريخ البداية", "date"], ["endsAt", "تاريخ النهاية", "date"], ["budgetIls", "ميزانية توضيحية", "number"], ["contractor", "الجهة المنفذة"]],
  facilities: [["name", "اسم المرفق"], ["slug", "الرابط"], ["category", "الفئة"], ["description", "الوصف", "textarea"], ["address", "العنوان"], ["latitude", "خط العرض", "number"], ["longitude", "خط الطول", "number"], ["hours", "ساعات العمل"], ["phone", "الهاتف"]],
  news: [["title", "العنوان"], ["slug", "الرابط"], ["excerpt", "الملخص", "textarea"], ["body", "المحتوى", "textarea"], ["imageUrl", "رابط صورة الغلاف"], ["status", "حالة النشر", ["DRAFT", "PUBLISHED", "ARCHIVED"]]],
  events: [["title", "اسم الفعالية"], ["slug", "الرابط"], ["description", "الوصف", "textarea"], ["locationName", "الموقع"], ["latitude", "خط العرض", "number"], ["longitude", "خط الطول", "number"], ["startsAt", "وقت البداية", "datetime"], ["endsAt", "وقت النهاية", "datetime"], ["status", "حالة النشر", ["DRAFT", "PUBLISHED", "ARCHIVED"]]],
  announcements: [["title", "العنوان"], ["body", "النص", "textarea"], ["priority", "الأولوية", ["NORMAL", "IMPORTANT", "URGENT"]], ["status", "حالة النشر", ["DRAFT", "PUBLISHED", "ARCHIVED"]]],
  surveys: [["title", "عنوان الاستطلاع"], ["description", "الوصف", "textarea"], ["options", "الخيارات — كل خيار بسطر", "array"], ["status", "الحالة", ["DRAFT", "OPEN", "CLOSED"]], ["endsAt", "موعد الإغلاق", "date"]],
  employees: [["name", "الاسم"], ["department", "الإدارة"], ["title", "المسمى الوظيفي"]],
  users: [["name", "الاسم"], ["email", "البريد الإلكتروني"], ["phone", "الهاتف"], ["password", "كلمة مرور أولية", "password"], ["role", "الدور", ["CITIZEN", "STAFF", "EDITOR", "ADMIN"]]],
  notifications: [["title", "عنوان الإشعار"], ["body", "نص الإشعار", "textarea"], ["type", "النوع", ["GENERAL", "ALERT", "ANNOUNCEMENT", "REQUEST_UPDATE"]], ["userId", "معرّف المستخدم (فارغ لإشعار عام)"]]
};
const statusLabel: Record<string, string> = { NEW: "جديد", UNDER_REVIEW: "قيد المراجعة", IN_PROGRESS: "قيد التنفيذ", WAITING_CITIZEN: "بانتظار المواطن", COMPLETED: "مكتمل", REJECTED: "مرفوض", CANCELLED: "ملغي", RECEIVED: "تم الاستلام", PROCESSING: "قيد المعالجة", RESOLVED: "تم الحل", ACTIVE: "نشط", INACTIVE: "متوقف", DRAFT: "مسودة", PUBLISHED: "منشور", ARCHIVED: "مؤرشف", PLANNED: "مخطط", PAUSED: "متوقف", OPEN: "مفتوح", CLOSED: "مغلق", REQUESTED: "مطلوب", CONFIRMED: "مؤكد" };
export default function AdminWorkspace() {
  const pathname = usePathname(); const section = pathname.split("/")[2] || "overview"; const [user, setUser] = useState<Data | null>(null); const [checked, setChecked] = useState(false); const [rows, setRows] = useState<Data[]>([]); const [stats, setStats] = useState<Data | null>(null); const [mapFeatures, setMapFeatures] = useState<MapFeature[]>([]); const [mapCenter, setMapCenter] = useState({ longitude: 34.4032, latitude: 31.4394 }); const [mapZoom, setMapZoom] = useState(14.8); const [modal, setModal] = useState<Data | null>(null); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [municipality, setMunicipality] = useState<MunicipalityProfile | null>(null);
  const resource = section === "audit-log" ? "audit-log" : section;
  const readData = useCallback(async () => {
    if (["overview", "analytics"].includes(section)) { const response = await fetch("/api/analytics"); const result = response.ok ? await response.json() : null; setStats(result?.data || null); return; }
    if (section === "map-data") { const response = await fetch("/api/map-data"); const result = response.ok ? await response.json() : {}; setMapFeatures([...(result.projects || []), ...(result.facilities || []), ...(result.complaints || [])]); if (result.center) setMapCenter(result.center); if (typeof result.zoom === "number") setMapZoom(result.zoom); return; }
    if (section === "settings") { const response = await fetch("/api/municipality"); const result = response.ok ? await response.json() : null; setMunicipality(result?.municipality || null); return; }
    if (section === "municipalities") { const response = await fetch("/api/municipalities"); const result = response.ok ? await response.json() : { data: [] }; setRows(result.data || []); return; }
    if (["admin"].includes(section)) return;
    const endpoint = section === "audit-log" ? "audit-log" : resource;
    const response = await fetch(`/api/${endpoint}`); const result = response.ok ? await response.json() : null; setRows(result?.data || []);
  }, [section, resource]);
  useEffect(() => { fetch("/api/auth/me").then((r) => r.ok ? r.json() : null).then((r) => setUser(r?.user || null)).catch(() => setUser(null)).finally(() => setChecked(true)); }, []);
  useEffect(() => { if (user) readData().catch(() => undefined); }, [user, readData]);
  const isAdmin = Boolean(user && ["ADMIN", "SUPER_ADMIN"].includes(String(user.role)));
  const columns = useMemo(() => rows.length ? Object.keys(rows[0]).filter((key) => !["payload", "municipalityId", "citizenId", "userId", "serviceId", "updatedAt", "data"].includes(key)).slice(0, 7) : [], [rows]);
  async function removeRow(id: string) { if (!window.confirm("هل تريد حذف هذا السجل؟ لا يمكن التراجع عن هذا الإجراء.")) return; const response = await fetch(`/api/${resource}/${id}`, { method: "DELETE" }); const result = await response.json(); setNotice(response.ok ? "تم حذف السجل." : result.error || "تعذر الحذف"); await readData(); }
  async function submitForm(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setNotice(""); const form = new FormData(event.currentTarget); const body: Data = {};
    const formFields = fields[section] || (section === "settings" ? [["name", ""], ["description", ""], ["phone", ""], ["email", ""], ["address", ""], ["latitude", "", "number"], ["longitude", "", "number"], ["logoUrl", ""], ["brandPrimary", ""], ["brandSecondary", ""]] as [string, string, unknown?][] : section === "municipalities" ? [["name", ""], ["slug", ""], ["description", "", "textarea"], ["phone", ""], ["email", ""], ["address", ""], ["latitude", "", "number"], ["longitude", "", "number"], ["brandPrimary", ""], ["brandSecondary", ""]] as [string, string, unknown?][] : []);
    for (const [key, value] of form.entries()) { const field = formFields.find((item) => item[0] === key); const type = field?.[2]; if (type === "number" || ["latitude", "longitude", "progress", "durationDays", "feeIls", "budgetIls", "mapZoom"].includes(key)) body[key] = Number(value); else if (type === "array") body[key] = String(value).split(/\r?\n/).map((item) => item.trim()).filter(Boolean); else if (type === "date" || type === "datetime") body[key] = value ? new Date(String(value)).toISOString() : null; else if (typeof value === "string" && value !== "") body[key] = value; }
    try {
      if (section === "settings") { const response = await fetch("/api/municipality", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "تعذر حفظ الإعدادات"); setNotice("تم حفظ إعدادات البلدية."); await readData(); }
      else { const isEdit = Boolean(modal?.id); const url = section === "municipalities" ? "/api/municipalities" : isEdit ? `/api/${resource}/${modal!.id}` : `/api/${resource}`; const response = await fetch(url, { method: isEdit ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "تعذر حفظ السجل"); setNotice("تم الحفظ بنجاح."); setModal(null); await readData(); }
    } catch (error) { setNotice(error instanceof Error ? error.message : "تعذر الاتصال بالخادم"); } finally { setBusy(false); }
  }
  async function updateStatus(row: Data, status: string) { const response = await fetch(`/api/${resource}/${row.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const result = await response.json(); setNotice(response.ok ? "تم تحديث الحالة." : result.error || "تعذر التحديث"); await readData(); }
  if (!checked) return <main className="page-content"><div className="empty-state">جارٍ التحقق من الصلاحية...</div></main>;
  if (!user) return <main className="page-content"><div className="auth-required"><h2>بوابة الإدارة</h2><p>سجّل الدخول بحساب موظف مخوّل.</p><Link href="/login" className="button button-primary">تسجيل الدخول ←</Link></div></main>;
  if (!isAdmin && !["STAFF", "EDITOR"].includes(String(user.role))) return <main className="page-content"><div className="auth-required"><h2>لا تملك صلاحية دخول هذه الصفحة</h2><Link href="/account" className="button button-outline">العودة إلى حساب المواطن</Link></div></main>;
  const canEdit = isAdmin || String(user.role) === "EDITOR" && ["services", "projects", "facilities", "news", "events", "announcements", "surveys"].includes(section) || String(user.role) === "STAFF" && ["requests", "complaints", "appointments"].includes(section);
  const canDelete = isAdmin && section !== "audit-log";
  return <main className="admin-shell"><aside className="admin-sidebar"><div className="admin-sidebar-head"><small>Municipality OS / ADMIN</small><strong>إدارة البلدية</strong></div><nav>{sections.filter(([, key]) => (key !== "municipalities" || user.role === "SUPER_ADMIN") && (!["users", "audit-log"].includes(key) || user.role === "SUPER_ADMIN" || user.role === "ADMIN")).map(([label, key, icon]) => <Link href={`/admin${key === "overview" ? "" : `/${key}`}`} className={section === key || (section === "overview" && key === "overview") ? "active" : ""} key={key}><span>{icon}</span>{label}</Link>)}</nav></aside><section className="admin-main"><div className="admin-topline"><div><h1>{names[section] || "لوحة الإدارة"}</h1><p>{String(((user as Data).municipality as Data | null)?.name || "بلدية البريج")} · وضع تجريبي</p></div><span className="demo-label">بيانات تجريبية</span></div>{notice && <div className="form-success" role="status" style={{ marginBottom: 12 }}>{notice}</div>}
    {(section === "overview" || section === "analytics") && <><div className="metric-grid"><article className="metric-card"><small>الطلبات الجديدة</small><strong>{String(((stats?.requests || {}) as Data).NEW ?? 0)}</strong><span>بيانات تجريبية</span></article><article className="metric-card"><small>الشكاوى المفتوحة</small><strong>{String(Object.entries((stats?.complaints || {}) as Data).filter(([status]) => !["RESOLVED", "REJECTED"].includes(status)).reduce((sum, [, value]) => sum + Number(value), 0))}</strong><span>ضمن البلدية الحالية</span></article><article className="metric-card"><small>الخدمات النشطة</small><strong>{String(stats?.services ?? "—")}</strong><span>من كتالوج البلدية</span></article><article className="metric-card"><small>المشاريع</small><strong>{String(stats?.projects ?? "—")}</strong><span>مؤشرات تجريبية</span></article></div><div className="surface"><h2>مساحات العمل</h2><div className="admin-section-links">{sections.slice(1).filter(([, key]) => key !== "municipalities" || user.role === "SUPER_ADMIN").map(([label, key, icon]) => <Link key={key} className="admin-section-link" href={`/admin/${key}`}><span>{icon}</span>{label} <i style={{ marginRight: "auto" }}>←</i></Link>)}</div></div></>}
    {section === "settings" && municipality && <section className="surface"><h2>هوية البلدية</h2><p>تنعكس الألوان وساعات العمل ومركز الخريطة على واجهة البوابة العامة.</p><form className="settings-form" onSubmit={submitForm}><div className="settings-fields">{[["name", "اسم البلدية", municipality.name], ["description", "الوصف", municipality.description], ["phone", "الهاتف", municipality.phone], ["email", "البريد الإلكتروني", municipality.email], ["address", "العنوان", municipality.address], ["latitude", "خط العرض", municipality.latitude], ["longitude", "خط الطول", municipality.longitude], ["logoUrl", "رابط الشعار", municipality.logoUrl || ""], ["brandPrimary", "اللون الأساسي", municipality.brandPrimary], ["brandSecondary", "اللون الثانوي", municipality.brandSecondary], ["businessHours", "ساعات العمل", municipality.settings?.businessHours || "الأحد–الخميس، 08:00–15:00"], ["mapZoom", "مستوى تقريب الخريطة (10–18)", municipality.settings?.mapZoom || 14.8]].map(([name, label, value]) => <label className="form-field" key={name as string}>{label as string}<input name={name as string} defaultValue={String(value ?? "")} type={name === "latitude" || name === "longitude" || name === "mapZoom" ? "number" : "text"} step={name === "latitude" || name === "longitude" || name === "mapZoom" ? "any" : undefined} min={name === "mapZoom" ? 10 : undefined} max={name === "mapZoom" ? 18 : undefined} required={name !== "logoUrl"} /></label>)}</div><button className="button button-primary" disabled={busy || !canEdit}>حفظ الإعدادات ←</button></form></section>}
    {section === "map-data" && <section className="surface"><div className="content-toolbar"><div><h2>طبقات مواقع المدينة</h2><p>انقر عنصرًا لتحريك الكاميرا وإظهار تفاصيله.</p></div><span className="demo-label">طبقات تجريبية</span></div><div style={{ height: 510 }}><MapView features={mapFeatures} center={mapCenter} initialZoom={mapZoom} compact /></div></section>}
    {section === "municipalities" && <><div className="content-toolbar"><p>إنشاء المستأجرين متاح لمسؤول النظام الأعلى فقط.</p><button className="button button-primary" onClick={() => setModal({})} disabled={String(user.role) !== "SUPER_ADMIN"}>+ بلدية جديدة</button></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>الاسم</th><th>الرابط</th><th>تاريخ الإنشاء</th></tr></thead><tbody>{rows.map((row) => <tr key={String(row.id)}><td>{String(row.name)}</td><td>{String(row.slug)}</td><td>{new Date(String(row.createdAt)).toLocaleDateString("ar-PS")}</td></tr>)}</tbody></table></div></>}
    {!(["overview", "analytics", "settings", "map-data", "municipalities"].includes(section)) && <><div className="content-toolbar"><div><h2>{names[section]}</h2><p>إدارة سجل البلدية وعرض البيانات المخزنة في PostgreSQL.</p></div>{canEdit && fields[section] && <button className="button button-primary" onClick={() => setModal({})}>+ إضافة {titles[section] || "سجل"}</button>}</div>{rows.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr>{columns.map((key) => <th key={key}>{fieldLabel(key)}</th>)}<th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>{rows.map((row) => <tr key={String(row.id)}>{columns.map((key) => <td key={key}>{displayValue(row[key])}</td>)}<td>{typeof row.status === "string" ? <select aria-label="تحديث الحالة" className="status-select" value={String(row.status)} onChange={(event) => updateStatus(row, event.target.value)} disabled={!canEdit || ["audit-log"].includes(section)}>{statusesFor(section, String(row.status)).map((status) => <option value={status} key={status}>{statusLabel[status] || status}</option>)}</select> : "—"}</td><td><div className="table-actions">{canEdit && fields[section] && <button onClick={() => setModal(row)}>تعديل</button>}{canDelete && <button onClick={() => removeRow(String(row.id))}>حذف</button>}</div></td></tr>)}</tbody></table></div> : <div className="empty-state"><strong>لا توجد سجلات بعد</strong>أضف محتوى من الزر أعلاه أو ابدأ باستخدام البوابة لتظهر البيانات هنا.</div>}</>}
    <div className="admin-disclaimer">جميع البيانات والأرقام والمواقع في هذه البيئة تجريبية. <Link href="/about">عن المنصة</Link></div>
  </section>{modal && <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="تحرير سجل"><form className="admin-edit-form" onSubmit={submitForm}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><h2>{modal.id ? `تعديل ${titles[section] || "السجل"}` : `إضافة ${titles[section] || "سجل"}`}</h2><button type="button" onClick={() => setModal(null)} className="modal-close" aria-label="إغلاق">×</button></div><div className="form-stack">{(section === "municipalities" ? [["name", "اسم البلدية"], ["slug", "الرابط المختصر"], ["description", "الوصف", "textarea"], ["phone", "الهاتف"], ["email", "البريد"], ["address", "العنوان"], ["latitude", "خط العرض", "number"], ["longitude", "خط الطول", "number"], ["brandPrimary", "اللون الأساسي"], ["brandSecondary", "اللون الثانوي"]] as [string, string, unknown?][] : fields[section] || []).map(([name, label, type]) => <label className="form-field" key={name}>{label}{Array.isArray(type) ? <select name={name} defaultValue={String(modal[name] || type[0])}>{type.map((option) => <option key={String(option)} value={String(option)}>{statusLabel[String(option)] || String(option)}</option>)}</select> : type === "textarea" || type === "array" ? <textarea name={name} defaultValue={Array.isArray(modal[name]) ? (modal[name] as string[]).join("\n") : String(modal[name] || "")} required={name !== "documents"} /> : <input name={name} type={type === "number" ? "number" : type === "date" ? "date" : type === "datetime" ? "datetime-local" : type === "password" ? "password" : "text"} step={type === "number" ? "any" : undefined} defaultValue={type === "date" && modal[name] ? new Date(String(modal[name])).toISOString().slice(0, 10) : type === "datetime" && modal[name] ? new Date(String(modal[name])).toISOString().slice(0, 16) : String(modal[name] || "")} required={!modal.id && name !== "icon" && name !== "documents"} />}</label>)}</div><div className="modal-actions"><button className="button button-primary" disabled={busy}>{busy ? "جارٍ الحفظ..." : "حفظ السجل"}</button><button type="button" className="button button-outline" onClick={() => setModal(null)}>إلغاء</button></div></form></div>}</main>;
}
function fieldLabel(key: string) { const map: Record<string, string> = { name: "الاسم", title: "العنوان", slug: "الرابط", category: "الفئة", status: "الحالة", createdAt: "تاريخ الإنشاء", referenceNo: "رقم المرجع", startsAt: "الموعد", progress: "الإنجاز", description: "الوصف", email: "البريد", role: "الدور", action: "الإجراء", entity: "الكيان" }; return map[key] || key; }
function displayValue(value: unknown) { if (value === null || value === undefined) return "—"; if (typeof value === "object") return JSON.stringify(value); if (typeof value === "string" && value.includes("T") && !Number.isNaN(Date.parse(value))) return new Date(value).toLocaleDateString("ar-PS"); return String(value); }
function statusesFor(resource: string, current: string) { const states: Record<string, string[]> = { requests: ["NEW", "UNDER_REVIEW", "IN_PROGRESS", "WAITING_CITIZEN", "COMPLETED", "REJECTED", "CANCELLED"], complaints: ["NEW", "RECEIVED", "PROCESSING", "RESOLVED", "REJECTED"], projects: ["PLANNED", "IN_PROGRESS", "COMPLETED", "PAUSED"], appointments: ["REQUESTED", "CONFIRMED", "COMPLETED", "CANCELLED"], proposals: ["RECEIVED", "REVIEWING", "ACCEPTED", "DECLINED"], surveys: ["DRAFT", "OPEN", "CLOSED"], services: ["ACTIVE", "INACTIVE"], news: ["DRAFT", "PUBLISHED", "ARCHIVED"], events: ["DRAFT", "PUBLISHED", "ARCHIVED"], announcements: ["DRAFT", "PUBLISHED", "ARCHIVED"] }; const list = states[resource] || [current]; return list.includes(current) ? list : [current, ...list]; }
