"use client";
import Link from "next/link";
import dynamic from "next/dynamic";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import { demoServices, mapCenter } from "@/lib/demo-data";
import type { CityService } from "@/types";
const MapView = dynamic(() => import("@/components/MapView"), { ssr: false });
type AccountUser = { id: string; name: string; email: string; role: string };
type RecordRow = Record<string, unknown>;
const tabs = [{ key: "", label: "نظرة عامة", icon: "◫" }, { key: "requests", label: "طلباتي", icon: "▤" }, { key: "complaints", label: "شكاواي", icon: "⚑" }, { key: "appointments", label: "مواعيدي", icon: "◷" }, { key: "notifications", label: "الإشعارات", icon: "◉" }, { key: "documents", label: "مستنداتي", icon: "▱" }];
const requestStatus: Record<string, string> = { NEW: "جديد", UNDER_REVIEW: "قيد المراجعة", IN_PROGRESS: "قيد التنفيذ", WAITING_CITIZEN: "بانتظارك", COMPLETED: "مكتمل", REJECTED: "مرفوض", CANCELLED: "ملغي" };
const complaintStatus: Record<string, string> = { NEW: "جديد", RECEIVED: "تم الاستلام", PROCESSING: "قيد المعالجة", RESOLVED: "تم الحل", REJECTED: "مرفوض" };
export default function CitizenWorkspace() {
  const pathname = usePathname(); const section = pathname.split("/")[2] || ""; const [user, setUser] = useState<AccountUser | null>(null); const [checked, setChecked] = useState(false); const [rows, setRows] = useState<RecordRow[]>([]); const [services, setServices] = useState<CityService[]>(demoServices); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [location, setLocation] = useState(mapCenter); const [file, setFile] = useState<File | null>(null); const [requestService, setRequestService] = useState(""); const [dashboardCounts, setDashboardCounts] = useState({ complaints: 0, appointments: 0, notifications: 0 });
  const onLocationSelect = useCallback((point: { longitude: number; latitude: number }) => setLocation(point), []);
  const title = tabs.find((item) => item.key === section)?.label || "نظرة عامة";
  const resource = section === "requests" || section === "" ? "requests" : section === "complaints" || section === "documents" ? "complaints" : section === "appointments" ? "appointments" : section === "notifications" ? "notifications" : "";
  const load = useCallback(async () => { if (!resource) return; try { const response = await fetch(`/api/${resource}`); const data = response.ok ? await response.json() : { data: [] }; setRows(data.data || []); } catch { setRows([]); } }, [resource]);
  useEffect(() => {
    fetch("/api/auth/me").then((r) => r.ok ? r.json() : null).then((r) => setUser(r?.user || null)).catch(() => setUser(null)).finally(() => setChecked(true));
    const requested = new URLSearchParams(window.location.search).get("new");
    fetch("/api/services").then((r) => r.ok ? r.json() : null).then((r) => { if (Array.isArray(r?.data)) { const nextServices: CityService[] = (r.data as RecordRow[]).map((x) => ({ id: String(x.id), slug: String(x.slug), name: String(x.name), category: String(x.category), description: String(x.description), duration: `${x.durationDays} أيام عمل`, fee: Number(x.feeIls) ? "رسوم تجريبية" : "دون رسوم", status: String(x.status) as CityService["status"], requirements: x.requirements as string[], steps: x.steps as string[], icon: String(x.icon || "✦") })); setServices(nextServices); const requestedService = nextServices.find((item) => item.slug === requested); if (requestedService) setRequestService(requestedService.id); } }).catch(() => undefined);
  }, []);
  useEffect(() => { if (user) load(); }, [user, load]);
  useEffect(() => { if (user && section === "") Promise.all(["complaints", "appointments", "notifications"].map((name) => fetch(`/api/${name}`).then((r) => r.ok ? r.json() : { data: [] }).catch(() => ({ data: [] })))).then((results) => setDashboardCounts({ complaints: results[0].data.length, appointments: results[1].data.length, notifications: results[2].data.filter((row: RecordRow) => !row.readAt).length })); }, [user, section]);
  async function submitRequest(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setBusy(true); setNotice(""); try { const response = await fetch("/api/requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ serviceId: form.get("serviceId"), title: form.get("title"), description: form.get("description"), payload: {} }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "تعذر إرسال الطلب"); setNotice(`تم استلام طلبك برقم ${result.data.referenceNo}`); formElement.reset(); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "تعذر الاتصال بالمنصة"); } finally { setBusy(false); } }
  async function uploadComplaintImage() { if (!file) return ""; const body = new FormData(); body.append("file", file); const response = await fetch("/api/uploads", { method: "POST", body }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "تعذر رفع الصورة"); return String(result.url); }
  async function submitComplaint(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setBusy(true); setNotice(""); try { const imageUrl = await uploadComplaintImage(); const response = await fetch("/api/complaints", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: form.get("title"), description: form.get("description"), category: form.get("category"), latitude: location.latitude, longitude: location.longitude, imageUrls: imageUrl ? [imageUrl] : [] }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "تعذر إرسال الشكوى"); setNotice(`تم تسجيل شكواك برقم ${result.data.referenceNo}`); formElement.reset(); setFile(null); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "تعذر الاتصال بالمنصة"); } finally { setBusy(false); } }
  async function submitAppointment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setBusy(true); setNotice(""); try { const response = await fetch("/api/appointments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ serviceName: form.get("serviceName"), startsAt: new Date(String(form.get("startsAt"))).toISOString(), notes: form.get("notes") }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "تعذر حجز الموعد"); setNotice(`تم تسجيل طلب الموعد برقم ${result.data.referenceNo}`); formElement.reset(); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "تعذر الاتصال بالمنصة"); } finally { setBusy(false); } }
  async function cancel(id: string) { const response = await fetch(`/api/requests/${id}/cancel`, { method: "POST" }); const result = await response.json(); setNotice(response.ok ? "تم إلغاء الطلب." : result.error || "تعذر إلغاء الطلب."); await load(); }
  async function markRead(id: string) { await fetch(`/api/notifications/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ readAt: new Date().toISOString() }) }); await load(); }
  if (!checked) return <main className="page-content"><div className="empty-state">جارٍ التحقق من الجلسة...</div></main>;
  if (!user) return <main className="page-content"><section className="auth-required"><span className="tile-icon">◉</span><h2>سجّل الدخول إلى بوابة المواطن</h2><p>تحتاج إلى حساب لتقديم الطلبات والشكاوى وحجز المواعيد ومراجعة الإشعارات.</p><Link className="button button-primary" href="/login">تسجيل الدخول ←</Link><Link className="button button-outline" href="/register">إنشاء حساب</Link></section></main>;
  return <><section className="page-hero"><div className="breadcrumbs"><Link href="/">الرئيسية</Link> / حساب المواطن</div><h1>{title}</h1><p>مرحبًا {user.name}، تابع معاملاتك وخدماتك من مساحة آمنة مرتبطة بحسابك.</p></section><main className="page-content account-shell"><aside className="account-nav surface"><div className="account-person"><span className="user-avatar">{user.name.slice(0, 1)}</span><div><strong>{user.name}</strong><small>مواطن · بيانات الحساب خاصة بك</small></div></div><nav>{tabs.map((tab) => <Link className={tab.key === section ? "active" : ""} href={tab.key ? `/account/${tab.key}` : "/account"} key={tab.key}><span>{tab.icon}</span>{tab.label}{tab.key === "notifications" && rows.filter((item) => !item.readAt).length > 0 && <small>{rows.filter((item) => !item.readAt).length}</small>}</Link>)}</nav><button className="signout-link" onClick={async () => { await fetch("/api/auth/logout", { method: "POST" }); window.location.assign("/"); }}>↪ تسجيل الخروج</button></aside><section className="account-main"><div className="content-toolbar"><div><h2>{section === "" ? `أهلًا ${user.name.split(" ")[0]}` : title}</h2><p>{section === "" ? "هذه مساحة خاصة لمتابعة خدماتك البلدية." : "تتغير الحالات حسب تقدم الإجراء وتظهر لك في سجل المتابعة."}</p></div><span className="demo-label">حساب تجريبي</span></div>{notice && <div className={notice.startsWith("تم") ? "form-success" : "form-alert"} role="status">{notice}</div>}
    {section === "" && <><div className="metric-grid"><article className="metric-card"><small>طلباتي النشطة</small><strong>{rows.filter((r) => r.status !== "COMPLETED" && r.status !== "CANCELLED").length}</strong><span>تابع آخر تحديث</span></article><article className="metric-card"><small>شكاوى مسجلة</small><strong>{dashboardCounts.complaints}</strong><span>افتح سجل الشكاوى</span></article><article className="metric-card"><small>مواعيد مسجلة</small><strong>{dashboardCounts.appointments}</strong><span>اطلب موعدًا جديدًا</span></article><article className="metric-card"><small>إشعارات غير مقروءة</small><strong>{dashboardCounts.notifications}</strong><span>راجع التنبيهات</span></article></div><div className="account-shortcuts"><Link href="/account/requests?new=building-permit"><span>⌂</span><strong>طلب خدمة جديدة</strong><small>رخصة، صيانة، أو شهادة</small></Link><Link href="/account/complaints"><span>⚑</span><strong>إرسال شكوى</strong><small>حدد الموقع وأرفق صورة</small></Link><Link href="/account/appointments"><span>◷</span><strong>حجز موعد</strong><small>طلب موعد لدى البلدية</small></Link></div><div className="surface"><h3>أحدث الطلبات</h3><RecordList rows={rows.slice(0, 4)} kind="requests" onCancel={cancel} /></div></>}
    {section === "requests" && <><div className="two-col"><section className="surface"><span className="section-kicker">طلب إلكتروني</span><h3>ابدأ خدمة بلدية</h3><form className="form-stack" onSubmit={submitRequest}><label className="form-field">الخدمة<select name="serviceId" required value={requestService} onChange={(e) => setRequestService(e.target.value)}><option value="">اختر الخدمة</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select></label><label className="form-field">عنوان الطلب<input name="title" required minLength={4} maxLength={180} placeholder="اكتب عنوانًا واضحًا للطلب" /></label><label className="form-field">تفاصيل إضافية<textarea name="description" maxLength={5000} placeholder="المعلومات التي تساعد الفريق المختص على مراجعة الطلب..." /></label><button className="button button-primary" disabled={busy}>{busy ? "جارٍ الإرسال..." : "إرسال الطلب ←"}</button></form></section><section className="surface"><span className="section-kicker">رقم مرجعي</span><h3>رحلة الطلب</h3><div className="request-timeline">{["جديد", "قيد المراجعة", "قيد التنفيذ", "مكتمل"].map((label, index) => <div className={`timeline-row${index === 0 ? " done" : ""}`} key={label}><span className="timeline-dot" /><span><strong>{label}</strong><small>{index === 0 ? "يصلك رقم متابعة عند التقديم" : "تحديث عند انتقال الطلب للمرحلة"}</small></span></div>)}</div></section></div><section className="surface" style={{ marginTop: 14 }}><h3>سجل طلباتي</h3><RecordList rows={rows} kind="requests" onCancel={cancel} /></section></>}
    {section === "complaints" && <><div className="two-col"><section className="surface"><span className="section-kicker">مشاركة ميدانية</span><h3>إرسال شكوى أو بلاغ</h3><form className="form-stack" onSubmit={submitComplaint}><label className="form-field">عنوان الشكوى<input name="title" required minLength={4} maxLength={180} placeholder="مثال: عطل في إنارة الشارع" /></label><label className="form-field">التصنيف<select name="category"><option>الطرق والأرصفة</option><option>الإنارة</option><option>النظافة والنفايات</option><option>الحدائق</option><option>مياه وصرف صحي</option><option>أخرى</option></select></label><label className="form-field">وصف المشكلة<textarea name="description" required minLength={8} maxLength={5000} placeholder="اشرح ما حدث وما الذي يمكن أن يساعد في تحديد المشكلة..." /></label><div className="form-field"><span>صورة توضيحية (حتى 5MB)</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => setFile(e.target.files?.[0] || null)} /><small className="form-hint">{file ? file.name : "JPG أو PNG أو WebP — اختياري"}</small></div><button className="button button-primary" disabled={busy}>{busy ? "جارٍ الإرسال..." : "إرسال الشكوى ←"}</button></form></section><section className="surface complaint-location"><span className="section-kicker">تحديد الموقع</span><h3>أين تقع المشكلة؟</h3><p>انقر على الخريطة لوضع علامة، أو استخدم موقع جهازك.</p><div className="form-field" style={{ display: "flex", gap: 7 }}><input aria-label="خط العرض" type="number" step="any" value={location.latitude.toFixed(6)} onChange={(e) => setLocation((p) => ({ ...p, latitude: Number(e.target.value) }))} /><input aria-label="خط الطول" type="number" step="any" value={location.longitude.toFixed(6)} onChange={(e) => setLocation((p) => ({ ...p, longitude: Number(e.target.value) }))} /></div><div className="complaint-map"><MapView features={[]} center={mapCenter} compact onLocationSelect={onLocationSelect} /></div><button className="text-link location-button" type="button" onClick={() => { if (!navigator.geolocation) return setNotice("متصفحك لا يدعم تحديد الموقع."); navigator.geolocation.getCurrentPosition(({ coords }) => setLocation({ latitude: coords.latitude, longitude: coords.longitude }), () => setNotice("لم نتمكن من قراءة موقعك. استخدم الخريطة لتحديده.")); }}>⌖ استخدام موقعي الحالي</button></section></div><section className="surface" style={{ marginTop: 14 }}><h3>شكاواي السابقة</h3><RecordList rows={rows} kind="complaints" /></section></>}
    {section === "appointments" && <><div className="two-col"><section className="surface"><span className="section-kicker">موعد حضوري</span><h3>أرسل طلب موعد</h3><p>الموعد يخضع للتأكيد من البلدية. اختر تاريخًا خلال التسعين يومًا القادمة.</p><form className="form-stack" onSubmit={submitAppointment}><label className="form-field">الخدمة أو القسم<input name="serviceName" required minLength={2} placeholder="مثال: مراجعة قسم التراخيص" /></label><label className="form-field">التاريخ والوقت<input name="startsAt" type="datetime-local" required min={new Date(Date.now() + 3600_000).toISOString().slice(0, 16)} /></label><label className="form-field">ملاحظات<textarea name="notes" maxLength={1000} placeholder="سبب الموعد أو ما ترغب في إحضاره" /></label><button className="button button-primary" disabled={busy}>{busy ? "جارٍ التسجيل..." : "إرسال طلب الموعد ←"}</button></form></section><section className="surface"><h3>مواعيدي</h3><RecordList rows={rows} kind="appointments" /></section></div></>}
    {section === "notifications" && <section className="surface"><h3>الإشعارات</h3><div className="record-list">{rows.map((row) => <article className="record-row" key={String(row.id)}><span>◉</span><div><strong>{String(row.title)}</strong><small>{String(row.body)} · {new Date(String(row.createdAt)).toLocaleString("ar-PS")}</small></div>{row.readAt ? <span className="status-chip">مقروء</span> : row.userId ? <button onClick={() => markRead(String(row.id))}>تمييز كمقروء</button> : <span className="status-chip">إعلان عام</span>}</article>)}{rows.length === 0 && <div className="empty-state">لا توجد إشعارات جديدة.</div>}</div></section>}
    {section === "documents" && <section className="surface"><span className="section-kicker">المرفقات</span><h3>مستنداتي</h3><p>تظهر المرفقات التي أرسلتها ضمن الشكاوى. المرفقات محمية بجلسة الدخول ولا تكون عامة.</p><div className="record-list">{rows.flatMap((row) => (Array.isArray(row.imageUrls) ? row.imageUrls.map((url, index) => <a className="record-row" key={`${row.id}-${index}`} href={String(url)} target="_blank" rel="noreferrer"><span>▧</span><div><strong>مرفق شكوى</strong><small>رقم الشكوى {String(row.referenceNo)}</small></div><span>فتح ↗</span></a>) : []))}{rows.flatMap((row) => row && Array.isArray(row.imageUrls) ? row.imageUrls : []).length === 0 && <div className="empty-state">ستجد صور الشكاوى المرفوعة هنا.</div>}</div></section>}
  </section></main></>;
}
function RecordList({ rows, kind, onCancel }: { rows: RecordRow[]; kind: string; onCancel?: (id: string) => void }) {
  if (!rows.length) return <div className="empty-state">{kind === "requests" ? "لا توجد طلبات بعد. ابدأ خدمة من النموذج أعلاه." : kind === "complaints" ? "لا توجد شكاوى مسجلة في هذا الحساب." : "لا توجد مواعيد مسجلة."}</div>;
  return <div className="record-list">{rows.map((row) => { const status = String(row.status || "NEW"); const label = kind === "complaints" ? complaintStatus[status] : requestStatus[status] || status; return <article key={String(row.id)} className="record-row"><span>▤</span><div><strong>{String(row.title || row.serviceName || (row.service as RecordRow | undefined)?.name || row.referenceNo || "طلب بلدي")}</strong><small>{String(row.referenceNo || "")} · {new Date(String(row.createdAt || row.startsAt || Date.now())).toLocaleDateString("ar-PS")}</small>{Array.isArray(row.timeline) && <small>آخر تحديث: {String((row.timeline[row.timeline.length - 1] as RecordRow)?.message || "")}</small>}</div><span className="status-chip">{label}</span>{kind === "requests" && ["NEW", "UNDER_REVIEW"].includes(status) && onCancel && <button onClick={() => onCancel(String(row.id))}>إلغاء</button>}</article>; })}</div>;
}
