"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import dynamic from "next/dynamic";
import { demoFacilities, demoNews, demoProjects, mapCenter } from "@/lib/demo-data";
import type { MapFeature } from "@/types";
const MapView = dynamic(() => import("@/components/MapView"), { ssr: false });
type Section = "city-guide" | "news" | "events" | "transparency" | "participation" | "search" | "about";
const content: Record<Section, { title: string; description: string }> = {
  "city-guide": { title: "دليلك إلى مرافق المدينة.", description: "اكتشف المدارس والمراكز الصحية والحدائق والأسواق على الخريطة. معلومات هذا الدليل تجريبية." },
  news: { title: "أخبار وإعلانات المدينة.", description: "مساحة موحدة للأخبار والتنبيهات والرسائل البلدية. المحتوى هنا تجريبي للتوضيح." },
  events: { title: "المدينة تلتقي.", description: "تابع الفعاليات والأنشطة المجتمعية المعلنة ضمن بوابة المدينة." },
  transparency: { title: "صورة أوضح عن العمل البلدي.", description: "لوحة شفافية تجريبية تعرض المشاريع والخدمات ومؤشرات للتوضيح، ولا تمثل إحصاءات رسمية." },
  participation: { title: "صوتك جزء من القرار.", description: "شارك باقتراح أو رأي في استطلاع مجتمعي. أدوات المشاركة في هذه النسخة تعمل في بيئة تجريبية." },
  search: { title: "ابحث في المدينة.", description: "نتائج الخدمات والمشاريع والمرافق والأخبار المتاحة في المنصة." },
  about: { title: "منصة للمدينة، قابلة لكل بلدية.", description: "Municipality OS نظام متعدد البلديات يجمع بوابة المواطن وإدارة الخدمات والمشاريع والبيانات المكانية." }
};
type Survey = { id: string; title: string; description: string; options: { id: string; label: string; _count?: { responses: number } }[]; _count?: { responses: number }[] };
type NewsItem = { id: string; title: string; category?: string; excerpt?: string; body?: string; publishedAt?: string };
type EventItem = { id: string; title: string; description: string; locationName: string; startsAt: string };
type AnnouncementItem = { id: string; title: string; body: string; priority: string; publishedAt?: string };
export default function PublicSection({ section }: { section: Section }) {
  const [features, setFeatures] = useState<MapFeature[]>([...demoProjects, ...demoFacilities]); const [active, setActive] = useState<MapFeature | null>(null); const [filter, setFilter] = useState("الكل"); const [guideCenter, setGuideCenter] = useState(mapCenter); const [guideZoom, setGuideZoom] = useState(14.8);
  const [surveys, setSurveys] = useState<Survey[]>([]); const [notice, setNotice] = useState(""); const [proposalBusy, setProposalBusy] = useState(false);
  const [metrics, setMetrics] = useState<{ requests: number; complaints: number; services: number } | null>(null);
  const [newsItems, setNewsItems] = useState<NewsItem[]>(demoNews); const [eventItems, setEventItems] = useState<EventItem[]>([]); const [announcements, setAnnouncements] = useState<AnnouncementItem[]>([]); const [projects, setProjects] = useState<MapFeature[]>(demoProjects);
  const [q, setQ] = useState(""); const [query, setQuery] = useState(""); const [searchResults, setSearchResults] = useState<{ name: string; kind: string; href: string; description?: string }[]>([]);
  useEffect(() => {
    if (section === "city-guide") fetch("/api/map-data").then((r) => r.json()).then((data) => { const nextFeatures = [...(data.projects || demoProjects), ...(data.facilities || demoFacilities), ...(data.complaints || [])] as MapFeature[]; setFeatures(nextFeatures); if (data.center) setGuideCenter(data.center); if (typeof data.zoom === "number") setGuideZoom(data.zoom); const focus = new URLSearchParams(window.location.search).get("focus"); if (focus) setActive(nextFeatures.find((feature) => feature.id === focus) || null); }).catch(() => undefined);
    if (section === "news") fetch("/api/news").then((r) => r.ok ? r.json() : null).then((r) => { if (Array.isArray(r?.data)) setNewsItems(r.data); }).catch(() => undefined);
    if (section === "news") fetch("/api/announcements").then((r) => r.ok ? r.json() : null).then((r) => { if (r?.data) setAnnouncements(r.data); }).catch(() => undefined);
    if (section === "events") fetch("/api/events").then((r) => r.ok ? r.json() : null).then((r) => { if (Array.isArray(r?.data)) setEventItems(r.data); }).catch(() => undefined);
    if (section === "transparency") fetch("/api/projects").then((r) => r.ok ? r.json() : null).then((r) => { if (Array.isArray(r?.data)) setProjects(r.data); }).catch(() => undefined);
    if (section === "transparency") fetch("/api/transparency").then((r) => r.ok ? r.json() : null).then((r) => r?.data && setMetrics(r.data)).catch(() => undefined);
    if (section === "participation") fetch("/api/surveys").then((r) => r.ok ? r.json() : null).then((r) => r?.data && setSurveys(r.data)).catch(() => undefined);
    if (section === "search" && typeof window !== "undefined") { const initial = new URLSearchParams(window.location.search).get("q") || ""; setQ(initial); setQuery(initial); }
  }, [section]);
  useEffect(() => { if (section !== "search" || query.length < 2) return; fetch(`/api/search?q=${encodeURIComponent(query)}`).then((r) => r.json()).then((data) => setSearchResults(data.data || [])).catch(() => setSearchResults([])); }, [section, query]);
  const facilities = useMemo(() => features.filter((feature) => filter === "الكل" || feature.category === filter), [features, filter]);
  const current = content[section];
  async function submitProposal(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setProposalBusy(true); setNotice("");
    try { const response = await fetch("/api/proposals", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: form.get("title"), body: form.get("body"), category: form.get("category") }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "تعذر إرسال الاقتراح"); setNotice("وصل اقتراحك التجريبي، ورقم تسجيله " + result.data.id.slice(-6).toUpperCase()); formElement.reset(); }
    catch (error) { setNotice(error instanceof Error ? error.message : "تعذر الإرسال"); } finally { setProposalBusy(false); }
  }
  async function vote(survey: Survey, optionId: string) {
    try { const response = await fetch(`/api/surveys/${survey.id}/vote`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ optionId }) }); const result = await response.json(); if (!response.ok) { setNotice(result.error || "تعذر تسجيل التصويت"); return; } setNotice("تم تسجيل صوتك. شكرًا لمشاركتك."); const refreshed = await fetch("/api/surveys").then((r) => r.json()); setSurveys(refreshed.data || []); }
    catch { setNotice("تعذر الاتصال بالمنصة. جرّب لاحقًا."); }
  }
  return <><section className="page-hero"><div className="breadcrumbs"><Link href="/">الرئيسية</Link> / {current.title}</div><h1>{current.title}</h1><p>{current.description}</p></section><main className="page-content">
    {section === "city-guide" && <><div className="content-toolbar"><div><h2>أين تريد أن تذهب؟</h2><p>اختر موقعًا من القائمة لرؤيته على الخريطة.</p></div><span className="demo-label">مواقع تجريبية</span></div><div className="filter-chips" style={{ marginBottom: 13 }}>{["الكل", ...Array.from(new Set(features.map((item) => item.category)))].map((category) => <button key={category} className={`filter-chip${filter === category ? " active" : ""}`} onClick={() => setFilter(category)}>{category}</button>)}</div><div className="guide-layout"><div className="guide-map"><MapView features={features} center={guideCenter} initialZoom={guideZoom} activeId={active?.id} onSelect={setActive} compact /></div><div className="guide-list">{facilities.map((item) => <button key={item.id} className={`guide-item${active?.id === item.id ? " active" : ""}`} onClick={() => setActive(item)}><span className="tile-icon">{item.category === "مشروع بلدي" ? "◆" : "✦"}</span><span><strong>{item.name}</strong><small>{item.category} · بيانات تجريبية</small><small>{item.description}</small></span><em>↗</em></button>)}</div></div></>}
    {section === "transparency" && <><div className="demo-label" style={{ marginBottom: 14 }}>بيانات تجريبية — لا تمثل بيانات رسمية</div><div className="metric-grid"><article className="metric-card"><small>مشاريع مسجلة في العرض</small><strong>{String(projects.length).padStart(2, "0")}</strong><span>بيانات توضيحية</span></article><article className="metric-card"><small>خدمات ضمن الكتالوج</small><strong>{metrics?.services ?? 8}</strong><span>بيانات خدمة تجريبية</span></article><article className="metric-card"><small>طلبات قيد المعالجة</small><strong>{metrics?.requests ?? 1}</strong><span>بيانات Seed تجريبية</span></article><article className="metric-card"><small>بلاغات مسجلة</small><strong>{metrics?.complaints ?? 1}</strong><span>بيانات Seed تجريبية</span></article></div><div className="surface" style={{ marginTop: 15 }}><div className="content-toolbar"><div><h2>المشاريع البلدية</h2><p>مواقع ونسب معروضة توضيحيًا على الخريطة.</p></div><Link href="/city-guide" className="text-link">الخريطة التفاعلية ↗</Link></div><div className="content-grid">{projects.map((project) => <Link key={project.id} href={`/city-guide?focus=${encodeURIComponent(project.id)}`} className="project-transparency"><div style={{ display: "flex", justifyContent: "space-between" }}><strong>{project.name}</strong><span className="pill">{project.status || "قيد التنفيذ"}</span></div><p>{project.description}</p><div className="progress-track"><i style={{ width: `${project.progress || 0}%` }} /></div><div className="project-values"><small>نسبة إنجاز توضيحية</small><strong>{project.progress || 0}%</strong></div><small>عرض الموقع على الخريطة ↗</small></Link>)}</div></div><div className="page-bottom-cta"><div><strong>تابع خدمة أو أرسل بلاغًا</strong><p>تظهر الحالة وخطوات المعالجة في حساب المواطن.</p></div><Link href="/account" className="button button-primary">بوابة المواطن ←</Link></div></>}
    {section === "news" && <><div className="content-toolbar"><div><h2>آخر المستجدات</h2><p>الأخبار والإعلانات المنشورة تجريبيًا.</p></div><span className="demo-label">بيانات تجريبية</span></div><div className="news-grid">{newsItems.map((item) => <article className="news-card" key={item.id}><div className="news-visual"><span>{item.category || "خبر بلدي"}</span></div><small>{item.category || "خبر بلدي"}</small><h3>{item.title}</h3><p>{item.excerpt || item.body}</p><footer>{item.publishedAt ? new Date(item.publishedAt).toLocaleDateString("ar-PS") : "بيانات تجريبية"} · محتوى توضيحي</footer></article>)}</div><section className="surface" style={{ marginTop: 15 }}><h3>الإعلانات والتنبيهات</h3><div className="record-list"><div className="record-row"><span>◈</span><div><strong>بيانات المنصة وخدماتها تجريبية</strong><small>تنبيه توضيحي — لا تعتمد هذه المنصة كمصدر معلومات رسمية.</small></div><span className="status-chip">مهم</span></div>{announcements.map((item) => <article className="record-row" key={item.id}><span>!</span><div><strong>{item.title}</strong><small>{item.body} · {item.publishedAt ? new Date(item.publishedAt).toLocaleDateString("ar-PS") : "بيانات تجريبية"}</small></div><span className="status-chip">{item.priority === "URGENT" ? "عاجل" : item.priority === "IMPORTANT" ? "مهم" : "إعلان"}</span></article>)}</div></section></>}
    {section === "events" && <><div className="content-toolbar"><div><h2>الفعاليات القادمة</h2><p>أجندة مجتمعية توضيحية يمكن للبلدية نشر الفعاليات من لوحة الإدارة.</p></div><span className="demo-label">بيانات تجريبية</span></div><div className="news-grid">{(eventItems.length ? eventItems : [{ id: "demo-event", startsAt: new Date(Date.now() + 8 * 86400_000).toISOString(), title: "جلسة حوار مجتمعي حول المرافق", locationName: "قاعة البلدية — موقع تجريبي", description: "فعالية تجريبية" }]).map((event) => <article className="event-card" key={event.id}><div className="event-date"><strong>{new Date(event.startsAt).toLocaleDateString("ar-PS", { day: "2-digit" })}</strong><small>{new Date(event.startsAt).toLocaleDateString("ar-PS", { month: "short" })}</small></div><div><span className="demo-label">فعالية تجريبية</span><h3>{event.title}</h3><p>⌖ {event.locationName}</p><small>{event.description} · بيانات توضيحية</small></div></article>)}</div></>}
    {section === "participation" && <><div className="demo-label" style={{ marginBottom: 14 }}>المشاركة توضيحية، ونتائج الاستطلاع تجريبية.</div><div className="content-grid"><section className="surface"><span className="section-kicker">شارك بفكرة</span><h2>اقتراح للمدينة</h2><p>صف فكرة أو تحسينًا تتمنى رؤيته. يتطلب إرسال الاقتراح تسجيل الدخول.</p>{notice && <div className={notice.includes("تم تسجيل") || notice.includes("وصل اقتراح") ? "form-success" : "form-alert"} role="status">{notice}</div>}<form className="form-stack" onSubmit={submitProposal}><label className="form-field">عنوان الاقتراح<input name="title" required minLength={5} maxLength={160} placeholder="مثال: تحسين إنارة الحديقة العامة" /></label><label className="form-field">التصنيف<select name="category"><option>خدمات عامة</option><option>طرق وإنارة</option><option>نظافة وبيئة</option><option>حدائق ومرافق</option><option>خدمات رقمية</option></select></label><label className="form-field">الفكرة<textarea name="body" required minLength={15} maxLength={3000} placeholder="أخبرنا ما المشكلة وكيف يمكن تحسينها..." /></label><button className="button button-primary" disabled={proposalBusy}>{proposalBusy ? "جارٍ الإرسال..." : "إرسال الاقتراح ←"}</button></form></section><section className="surface"><span className="section-kicker">استطلاع مجتمعي</span><h2>ما الأولوية التي تستحق اهتمامًا أكبر؟</h2><p>صوت واحد لكل حساب مواطن. تسجيل الدخول مطلوب للمشاركة.</p>{surveys.length ? surveys.map((survey) => <article className="survey-card" key={survey.id}><h3>{survey.title}</h3><p>{survey.description}</p><div className="survey-options">{survey.options?.map((option) => <button key={option.id} onClick={() => vote(survey, option.id)}>{option.label}<span style={{ float: "left", color: "#86928c" }}>{option._count?.responses || 0}</span></button>)}</div><small>عدد الأصوات الموضح قد يكون تجريبيًا.</small></article>) : <div className="empty-state">لا يوجد استطلاع منشور حاليًا. <span className="demo-label">محتوى تجريبي</span></div>}</section></div></>}
    {section === "search" && <><div className="surface"><form className="form-stack" onSubmit={(event) => { event.preventDefault(); setQuery(q); }}><label className="form-field">ما الذي تبحث عنه؟<input value={q} onChange={(event) => setQ(event.target.value)} placeholder="خدمة، مشروع، مرفق..." /></label><button className="button button-primary">بحث ←</button></form></div><div className="record-list" style={{ marginTop: 15 }}>{searchResults.map((result, index) => <Link className="record-row" key={`${result.kind}-${index}`} href={result.href}><div><small>{result.kind}</small><strong>{result.name}</strong><small>{result.description}</small></div><span>↗</span></Link>)}{query.length > 1 && searchResults.length === 0 && <div className="empty-state">لا توجد نتائج مطابقة في البيانات المتاحة.</div>}</div></>}
    {section === "about" && <div className="content-grid"><section className="surface"><span className="section-kicker">Municipality OS</span><h2>منصة بلدية متعددة الجهات</h2><p>مشروع للبنية التشغيلية البلدية: واجهة عربية، REST API، قاعدة PostgreSQL/PostGIS، جلسات آمنة وصلاحيات مركزية، وخريطة تفاعلية. بلدية البريج هي بيئة العرض التجريبية الأولى.</p><div className="demo-label">البيانات والمواقع والرسوم والأرقام المعروضة تجريبية بالكامل.</div></section><section className="surface"><h3>مصادر الخريطة</h3><p>تعتمد طبقات الطرق والمباني على OpenStreetMap وOpenFreeMap، ويعرض MapLibre المباني بارتفاعات ثلاثية الأبعاد عند توفرها في بيانات الطبقة.</p><p>الأحوال الجوية والتاريخ والوقت الواردة في الصفحة الرئيسية للعرض التوضيحي. لا يتصل هذا الإصدار بخدمة طقس أو تنبيهات رسمية.</p><Link href="/services" className="button button-primary">استعرض الخدمات ←</Link></section></div>}
  </main></>;
}
